### ISSUE TITLE
Create Landing Page and Navigation Bar

### ISSUE THREAD

**Issue by ptayal76** [swciitg/college_cupid#1]
### Summary

Look at the design given in the README and create CampusCupid1.
Also modify the current Navigation bar in home.dart to look like in CampusCupid4.
Only the UI is expected from your side.
**NOTE: Do write comments wherever possible in your code**

**Comment by vivekreddy049** [comment]
i would like to work on this

**Comment by ptayal76** [comment]
You've been assigned @vivekreddy049
