### ISSUE TITLE
Create the UI of Profile Details Screen

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/college_cupid#2]
Create the page CampusCupid2 as given in the figma and redirect the user to this page when they press the "Continue with Outlook" button in the CampusCupid1 page.

**NOTE: Do write comments wherever possible.**

**Comment by vivekreddy049** [comment]
i would like to work on this

**Comment by ptayal76** [comment]
You've been assigned @vivekreddy049

**Comment by DahVik** [comment]
hey, I would like to contribute to this.

**Comment by ptayal76** [comment]
You've been assigned @DahVik
