### ISSUE TITLE
Use Text() to display Person's name.

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/college_cupid#21]
In HomeTab (CampusCupid4) the person's name should be displayed using a Text() widget. Also tapping on the image should redirect (use Navigator.push) the user to the ProfileTab (CampusCupid7) with isMine = false.

**Comment by DahVik** [comment]
Hey , i would like to work on this

**Comment by vivekreddy049** [comment]
i would like to work on this

**Comment by Mrudul111** [comment]
Could you assign me this issue?

**Comment by hardikroongta8** [comment]
Assigned to you @DahVik
