### ISSUE TITLE
Height of InterestCard

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/college_cupid#24]
The text in the InterestCard is getting clipped.
![WhatsApp Image 2023-10-03 at 22 44 30](https://github.com/swciitg/college_cupid/assets/95174582/9fe7c73e-8c08-4ed8-9d22-6bd653726fc8)

**Comment by venkylm10** [comment]
@hardikroongta8 assign it to me i will fix it, didn't came across this while building the about you screen

**Comment by hardikroongta8** [comment]
Assigned to you @venkylm10
