### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by ptayal76** [swciitg/college_cupid#3]
### Summary

Look at the design given in the README and create CampusCupid4.
Redirect the user to this page when he presses the Confirm button in CampusCupid3.
Only the UI is expected from your side

**NOTE: Do write comments wherever possible in your code**

**Comment by lazypanda2004** [comment]
I would like to work on this

**Comment by ptayal76** [comment]
assigned @lazypanda2004

**Comment by vivekreddy049** [comment]
@hardikroongta8 @ptayal76 
i would like to work on this
almost completed do assign me
Thank you
