### ISSUE TITLE
Create the UI for the About You screen.

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/college_cupid#4]
Create the page CampusCupid3 as given in the figma and redirect the user to this page when they press the "Continue" button in the CampusCupid2 page.

**NOTE: Do write comments wherever possible.**

**Comment by vivekreddy049** [comment]
i would like to work on this

**Comment by venkylm10** [comment]
can you assign it to me if no one is working on it!

**Comment by hardikroongta8** [comment]
Assigned to you @venkylm10
