### ISSUE TITLE
Update UI of Sign in with Outlook and Sign up screens

### ISSUE THREAD

**Issue by venkylm10** [swciitg/college_cupid#44]
Sign in with Outlook screen : https://www.figma.com/design/1q7Wq5JevYV2q3SbJ2gweP/College-Cupid?node-id=846-1056&t=l4lq92qx0dbBzVzA-4

Sign up screen : https://www.figma.com/design/1q7Wq5JevYV2q3SbJ2gweP/College-Cupid?node-id=846-1074&t=l4lq92qx0dbBzVzA-4

**Comment by Ayush-Dix** [comment]
Interested

**Comment by venkylm10** [comment]
@0000AYUSH0000 Assigned
