### ISSUE TITLE
User Details Screens 

### ISSUE THREAD

**Issue by venkylm10** [swciitg/college_cupid#45]
Update UI of User Details Screens

https://www.figma.com/design/1q7Wq5JevYV2q3SbJ2gweP/College-Cupid?node-id=853-1702&t=l4lq92qx0dbBzVzA-4

**Comment by venkylm10** [comment]
@Himadri2041  Assigned

**Comment by venkylm10** [comment]
@Himadri2041 Updates?

**Comment by Himadri2041** [comment]
Already pushed

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by venkylm10** [comment]
Merge with latest dev branch code

**Comment by Himadri2041** [comment]
Done


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
