### ISSUE TITLE
Create the UI for "Your Crushes" screen.

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/college_cupid#5]
Create the page CampusCupid6 as given in the figma.
The user should be redirected to this page whenever they press the heart icon (2nd) from the BottomNavigationBar.

**NOTE: Do write comments wherever possible**

**Comment by poonam-shelke1712** [comment]
i would like to work on this

**Comment by ptayal76** [comment]
assigned @NProblems

**Comment by poonam-shelke1712** [comment]
@ptayal76  please check the pull request for this issue and please let me know about any comments.
PR link: https://github.com/swciitg/college_cupid/pull/15
