### ISSUE TITLE
Create Filters BottomModalSheet

### ISSUE THREAD

**Issue by ptayal76** [swciitg/college_cupid#6]
Look at the design given in the README and Create the Bottom Modal Sheet in CampusCupid5. This sheet should open when the user presses the filter button in CampusCupid4.
Only UI is expected from your side.

**NOTE: Do write comments wherever possible in your code**

**Comment by amitsing8576** [comment]
I would like to work on this

**Comment by hardikroongta8** [comment]
Assigned to you @amitsing8576

**Comment by venkylm10** [comment]
if no ones working on it, @hardikroongta8 can you assign this to me

**Comment by hardikroongta8** [comment]
Assigned to you @venkylm10
