### ISSUE TITLE
Create the UI for Profile screen.

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/college_cupid#7]
Create the pages CampusCupid7 and CampusCupid9 as given in figma. 
The user should be redirected to CampusCupid7 page whenever they press any of the tile from CampusCupid4 page.
The user should be redirected to CampusCupid9 page whenever they press the profile icon (4th) in the BottomNavigationBar.

**NOTE: Do write comments wherever possible**

**Comment by DahVik** [comment]
Sir, can you assign this issue to me . I would like to contribute to this repository.

**Comment by ptayal76** [comment]
The issue has been assigned to you @DahVik

**Comment by Mrudul111** [comment]
Can I work on this issue? I would love to contribute for this project
