### ISSUE TITLE
Create Edit Profile Page

### ISSUE THREAD

**Issue by ptayal76** [swciitg/college_cupid#8]
### Summary

Look at the design given in the README and create CampusCupid8. Redirect user to this page when he presses the edit icon in CampusCupid9.
You can use components created in CampusCupid2 and CampusCupid3 to make this make.
Only UI is expected from your side.
**NOTE: Do write comments wherever possible in your code**

**Comment by lazypanda2004** [comment]
I would like to work on this

**Comment by hardikroongta8** [comment]
Assigned to you @lazypanda2004

**Comment by DahVik** [comment]
Hey, if no progress is there , please assign this to me

**Comment by hardikroongta8** [comment]
Assigned to you @DahVik
